env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
  "linebreak-style": 0,
  "consistent-return": 0,
  "global-require": 0,
  "eslint linebreak-style": [ 0, "error", "windows" ]
}
