on: push

jobs:
  eslint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: index.js
      - run: npm install
      - run: npm test
